### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by bshuler** [peerchemist/finta#103]
Simple example code does not function.

I expected there to be no error.

There is an error.

100%

finta~=1.2
pandas~=1.1.4
python 3.8

import pandas as pd
from finta import TA

candle_file = "bittrex_btc-usdt.csv"

candles = pd.read_csv(candle_file)

wto = TA.WTO(ohlc=candles, channel_lenght=11, average_lenght=15)

Error:

Traceback (most recent call last):
  File "C:/Users/me/PycharmProjects/project/build_indicators.py", line 8, in <module>
    wto = TA.WTO(ohlc=candles, channel_lenght=11, average_lenght=15)
  File "C:\Users\me\PycharmProjects\project\venv\lib\site-packages\finta\finta.py", line 13, in wrap
    i = 0 if isinstance(args[0], pd.DataFrame) else 1
IndexError: list index out of range

**Comment by bshuler** [comment]
1.0 does not have this bug, reverting to 1.0

**Comment by karthikdhanusu** [comment]
> 1.0 does not have this bug, reverting to 1.0

Perfect it worked
