### ISSUE TITLE
Resampling causes exception (with pandas 1.0.3)

### ISSUE THREAD

**Issue by ppawel** [peerchemist/finta#57]
I am trying to do simple resampling with the `resample`, like this:

`resample(data, "5d")`

Data contains just normal OHLC data, other calls like TA.ATR work on this data but `resample` and `resample_calendar` throw the following exception:

```
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    data = resample(data, "5d")
  File "/home/ppawel/.local/lib/python3.7/site-packages/finta/utils.py", line 19, in resample
    return df.resample(interval).agg(d)
  File "/home/ppawel/.local/lib/python3.7/site-packages/pandas/core/resample.py", line 281, in aggregate
    result, how = self._aggregate(func, *args, **kwargs)
  File "/home/ppawel/.local/lib/python3.7/site-packages/pandas/core/base.py", line 357, in _aggregate
    raise SpecificationError("nested renamer is not supported")
pandas.core.base.SpecificationError: nested renamer is not supported
```
I am currently using pandas 1.0.3 in this project.

Any hints or is that perhaps incompatibility with pandas 1.0?

Edit: I can confirm that it works as expected with pandas 0.25.

**Comment by peerchemist** [comment]
I've just tested with couple of datasets and it works as promised.

Maybe see this bug report:
https://github.com/pandas-dev/pandas/issues/32156

> it was caused by trying to aggregate a non-existent column. Version 1.0.3
