### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by relskhan** [peerchemist/finta#74]
I have tried and tried to format my panda dataframe to make this library work on it, but, I keep getting 'close' problems. I'll copy the error here along with the printout of my dataframe.

The error comes up from this line in the code:

`TA.SMA(dataTA, 42)`

```
                       date      open      high       low     close   volume
0       01/18/2020 17:00:00  0.000311  0.000311  0.000311  0.000311   1371.0
1       01/18/2020 17:01:00  0.000311  0.000311  0.000312  0.000312  13969.0
2       01/18/2020 17:02:00  0.000312  0.000312  0.000312  0.000312   2263.0
3       01/18/2020 17:03:00  0.000312  0.000311  0.000312  0.000312   8030.0
4       01/18/2020 17:04:00  0.000312  0.000311  0.000312  0.000311  11789.0
...                     ...       ...       ...       ...       ...      ...
276820  07/29/2020 14:42:00  0.000636  0.000636  0.000638  0.000636   2347.7
276821  07/29/2020 14:43:00  0.000636  0.000636  0.000637  0.000636   1028.5
276822  07/29/2020 14:44:00  0.000637  0.000637  0.000638  0.000637    442.4
276823  07/29/2020 14:45:00  0.000637  0.000636  0.000637  0.000636    399.9
276824  07/29/2020 14:46:00  0.000636  0.000634  0.000636  0.000634   2370.4

[276825 rows x 6 columns]
Traceback (most recent call last):
  File "/home/relskhan/anaconda3/envs/tesr/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'close'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ohlcGraphing.py", line 65, in <module>
    TA.SMA(dataTA, 42)
  File "/home/relskhan/anaconda3/envs/tesr/lib/python3.7/site-packages/finta/finta.py", line 18, in SMA
    ohlc[column].rolling(window=period).mean(),
  File "/home/relskhan/anaconda3/envs/tesr/lib/python3.7/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/relskhan/anaconda3/envs/tesr/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'close'

```
The one thing I'm curious about is how to formate that 'date' column. The example only shows by the day, I'm trying to get all the info by the minute and then use built in library to resample. I keep thinking that the date column has to be causing a problem here ... even though it says the 'close' column?

I'm using Python 3.7.6 in Anaconda, I pulled finTA from here.

**Comment by peerchemist** [comment]
Can you please send over the DataFrame you are using? I believe it's something inside it that is causing the error.
