### ISSUE TITLE
HMA function raising TypeError: apply() got an unexpected keyword argument 'raw' 

### ISSUE THREAD

**Issue by bwees** [peerchemist/finta#79]
When using the finta HMA function, ```finta.HMA(pricingData, 9)```, I get the following error:

```
Traceback (most recent call last):
  File "/Users/brandonwees/Documents/TradingRobot/.venv/bin/zipline", line 11, in <module>
    load_entry_point('zipline==1.4.0', 'console_scripts', 'zipline')()
  File "/Users/brandonwees/Documents/TradingRobot/.venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/brandonwees/Documents/TradingRobot/.venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/brandonwees/Documents/TradingRobot/.venv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/brandonwees/Documents/TradingRobot/.venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/brandonwees/Documents/TradingRobot/.venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/brandonwees/Documents/TradingRobot/.venv/lib/python3.6/site-packages/zipline/__main__.py", line 108, in _
    return f(*args, **kwargs)
  File "/Users/brandonwees/Documents/TradingRobot/.venv/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/brandonwees/Documents/TradingRobot/.venv/lib/python3.6/site-packages/zipline/__main__.py", line 317, in run
    benchmark_spec=benchmark_spec,
  File "/Users/brandonwees/Documents/TradingRobot/.venv/lib/python3.6/site-packages/zipline/utils/run_algo.py", line 216, in _run
    'script': algotext,
  File "/Users/brandonwees/Documents/TradingRobot/.venv/lib/python3.6/site-packages/zipline/algorithm.py", line 643, in run
    for perf in self.get_generator():
  File "/Users/brandonwees/Documents/TradingRobot/.venv/lib/python3.6/site-packages/zipline/gens/tradesimulation.py", line 205, in transform
    for capital_change_packet in every_bar(dt):
  File "/Users/brandonwees/Documents/TradingRobot/.venv/lib/python3.6/site-packages/zipline/gens/tradesimulation.py", line 133, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/Users/brandonwees/Documents/TradingRobot/.venv/lib/python3.6/site-packages/zipline/utils/events.py", line 218, in handle_data
    dt,
  File "/Users/brandonwees/Documents/TradingRobot/.venv/lib/python3.6/site-packages/zipline/utils/events.py", line 237, in handle_data
    self.callback(context, data)
  File "/Users/brandonwees/Documents/TradingRobot/.venv/lib/python3.6/site-packages/zipline/algorithm.py", line 454, in handle_data
    self._handle_data(self, data)
  File "bwees-zipline.py", line 92, in handle_data
    indicators = calculateIndicators(pricingData)
  File "bwees-zipline.py", line 45, in calculateIndicators
    pricingData = appendData(pricingData, ta.HMA(pricingData, 9))
  File "/Users/brandonwees/Documents/TradingRobot/.venv/lib/python3.6/site-packages/finta/finta.py", line 313, in HMA
    wmaf = cls.WMA(ohlc, period=half_length)
  File "/Users/brandonwees/Documents/TradingRobot/.venv/lib/python3.6/site-packages/finta/finta.py", line 293, in WMA
    wma = _close.apply(linear(weights), raw=True)
TypeError: apply() got an unexpected keyword argument 'raw'
```

This consistently happens with no sporadic behavior. I am using 28 other indicators from this library and have no errors with those.

**Versions:**

- Finta: 1.0, Mac in a venv
- Pandas: 0.22
- Python: 3.6

Here is a snippet of my OHLCV DataFrame

```
timestamp | open | high | low | close | volume
2015-06-23 00:00:00+00:00 | 124.922 | 125.049 | 124.333 | 124.481 | 30268863
2015-06-24 00:00:00+00:00 | 124.658 | 127.196 | 124.569 | 125.539 | 55280855
2015-06-25 00:00:00+00:00 | 126.274 | 126.608 | 124.942 | 124.942 | 31938100
2015-06-26 00:00:00+00:00 | 125.108 | 125.422 | 123.972 | 124.207 | 44066841
2015-06-29 00:00:00+00:00 | 122.943 | 123.932 | 121.982 | 122.031 | 49161427
2015-06-30 00:00:00+00:00 | 123.05 | 123.589 | 122.355 | 122.908 | 44370682
2015-07-01 00:00:00+00:00 | 124.354 | 124.393 | 123.462 | 124.06 | 30238811
2015-07-02 00:00:00+00:00 | 123.893 | 124.148 | 123.246 | 123.903 | 27210952
2015-07-06 00:00:00+00:00 | 122.433 | 123.697 | 122.345 | 123.472 | 28060431
2015-07-07 00:00:00+00:00 | 123.364 | 123.619 | 121.287 | 123.168 | 46946811
2015-07-08 00:00:00+00:00 | 121.982 | 122.139 | 120.081 | 120.111 | 60761614
2015-07-09 00:00:00+00:00 | 121.365 | 121.571 | 116.828 | 117.661 | 78595038
2015-07-10 00:00:00+00:00 | 119.493 | 121.365 | 118.778 | 120.806 | 61354474
2015-07-13 00:00:00+00:00 | 122.521 | 123.232 | 121.825 | 123.139 | 41440538
```

**Comment by peerchemist** [comment]
Is this still happening on your end?

**Comment by bwees** [comment]
I have not tried to fix it or resolve it as I eventually removed the need for it in my program.

Brandon Wees

**Comment by peerchemist** [comment]
Ok.
